on: 
  release:
    types: [created]
permissions:
  contents: write
  packages: write

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: rustup install 1.84.0
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: hackernews-{{ matrix.target }}
        if-no-files-found: error
        path: |
          target/release/hackernews-rust
          README.md
          config.json.example
