on: 
  release:
    types: [created]
permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: "1.78.0"
          EXTRA_FILES: "README.md config.json.example"

# https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases